### ISSUE TITLE
No Chinese voice

### ISSUE THREAD

**Issue by wuge0** [chcg/SpeechPlugin#1]

**Comment by chcg** [comment]
@TT-IPIP The plugin is using the installed windows voices. So this can't be fixed by the plugin itself. Currently the only description is:

>  "No kidding, Notepad++ speaks now. With SpeechPlugin, you can make Notepad++ dictate your text or source code. Of course, speakers are necessary.",

which should be extended here in a readme to be more clear how the speakers could be installed, see

https://support.microsoft.com/en-us/topic/how-to-download-text-to-speech-languages-for-windows-10-d5a6b612-b3ae-423f-afa5-4f6caf1ec5d3
